export {default as welcome} from "./getData/welcome.js"
export {default as project} from "./getData/project.js"
export {default as shopCar} from "./getData/shopCar.js"
export {default as order} from "./getData/order.js"
export {default as pc} from "./getData/pc.js"